### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Alberthchang** [jiaocoll/BeeScan-scan#2]
0.1:9007 127.0.0.1:9008 127.0.0.1:9009 127.0.0.1:9010 127.0.0.1:9030 127.0.0.1:9042 127.0.0.1:9050 127.0.0.1:9051 127.0.0.1:9080 127.0.0.1:9083 127.0.0.1:9090 127.0.0.1:9091 127.0.0.1:9100 127.0.0.1:U:9100 127.0.0.1:9151 127.0.0.1:9191 127.0.0.1:9200 127.0.0.1:9292 127.0.0.1:9295 127.0.0.1:9300 127.0.0.1:9306 127.0.0.1:9333 127.0.0.1:9334 127.0.0.1:9418 127.0.0.1:9443 127.0.0.1:9444 127.0.0.1:9446 127.0.0.1:9527 127.0.0.1:9530 127.0.0.1:9595 127.0.0.1:U:9600 127.0.0.1:9653 127.0.0.1:9668 127.0.0.1:9700 127.0.0.1:9711 127.0.0.1:9801 127.0.0.1:9864 127.0.0.1:9869 127.0.0.1:9870 127.0.0.1:9876 127.0.0.1:9943 127.0.0.1:9944 127.0.0.1:9981 127.0.0.1:9997 127.0.0.1:9999 127.0.0.1:10000 127.0.0.1:10001 127.0.0.1:U:10001 127.0.0.1:10003 127.0.0.1:10005 127.0.0.1:10030 127.0.0.1:10035 127.0.0.1:10162 127.0.0.1:10243 127.0.0.1:10250 127.0.0.1:10255 127.0.0.1:10332 127.0.0.1:10333 127.0.0.1:10443 127.0.0.1:10554 127.0.0.1:11001 127.0.0.1:11211 127.0.0.1:11300 127.0.0.1:11310 127.0.0.1:11371 127.0.0.1:11965 127.0.0.1:12000 127.0.0.1:12300 127.0.0.1:12345 127.0.0.1:12999 127.0.0.1:13579 127.0.0.1:13666 127.0.0.1:13720 127.0.0.1:13722 127.0.0.1:14000 127.0.0.1:14147 127.0.0.1:14265 127.0.0.1:14443 127.0.0.1:14534 127.0.0.1:15000 127.0.0.1:16000 127.0.0.1:16010 127.0.0.1:16030 127.0.0.1:16922 127.0.0.1:16923 127.0.0.1:16992 127.0.0.1:16993 127.0.0.1:17000 127.0.0.1:U:17185 127.0.0.1:17988 127.0.0.1:18000 127.0.0.1:18001 127.0.0.1:18080 127.0.0.1:18081 127.0.0.1:18086 127.0.0.1:18245 127.0.0.1:18246 127.0.0.1:18264 127.0.0.1:19150 127.0.0.1:19888 127.0.0.1:19999 127.0.0.1:U:20000 127.0.0.1:20000 127.0.0.1:20332 127.0.0.1:20547 127.0.0.1:20880 127.0.0.1:22105 127.0.0.1:22222 127.0.0.1:22335 127.0.0.1:23023 127.0.0.1:23424 127.0.0.1:25000 127.0.0.1:25010 127.0.0.1:25105 127.0.0.1:25565 127.0.0.1:26214 127.0.0.1:26470 127.0.0.1:27015 127.0.0.1:U:27015 127.0.0.1:27016 127.0.0.1:27017 127.0.0.1:28017 127.0.0.1:28080 127.0.0.1:U:28784 127.0.0.1:29876 127.0.0.1:29999 127.0.0.1:30001 127.0.0.1:U:30310 127.0.0.1:U:30311 127.0.0.1:U:30312 127.0.0.1:U:30313 127.0.0.1:U:30718 127.0.0.1:31337 127.0.0.1:32400 127.0.0.1:U:32768 127.0.0.1:32770 127.0.0.1:32771 127.0.0.1:32773 127.0.0.1:33338 127.0.0.1:33890 127.0.0.1:34567 127.0.0.1:34599 127.0.0.1:U:34962 127.0.0.1:U:34963 127.0.0.1:U:34964 127.0.0.1:37215 127.0.0.1:37777 127.0.0.1:40000 127.0.0.1:40001 127.0.0.1:41795 127.0.0.1:42873 127.0.0.1:44158 127.0.0.1:44818 127.0.0.1:U:44818 127.0.0.1:45554 127.0.0.1:U:47808 127.0.0.1:U:48899 127.0.0.1:49151 127.0.0.1:49152 127.0.0.1:49153 127.0.0.1:49154 127.0.0.1:49155 127.0.0.1:50000 127.0.0.1:50050 127.0.0.1:50060 127.0.0.1:50070 127.0.0.1:50075 127.0.0.1:50090 127.0.0.1:50100 127.0.0.1:50111 127.0.0.1:51106 127.0.0.1:52869 127.0.0.1:55442 127.0.0.1:55553 127.0.0.1:55555 127.0.0.1:U:59110 127.0.0.1:60001 127.0.0.1:60010 127.0.0.1:60030 127.0.0.1:60443 127.0.0.1:61613 127.0.0.1:61616 127.0.0.1:62078 127.0.0.1:64738]
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
BeeScan-scan/internal/runner.HandleTargets(0xc00000ce28, 0xc00000ce28)
	/Users/ameng/github/BeeScan-scan/internal/runner/runner.go:283 +0x8dd
main.main()
	/Users/ameng/github/BeeScan-scan/cmd/BeeScan-scan.go:101 +0x85

**Comment by jiaocoll** [comment]
已修复

**Comment by Alberthchang** [comment]
/24:23 202.96.17.1/24:25 202.96.17.1/24:37 202.96.17.1/24:42 202.96.17.1/24:49 202.96.17.1/24:53 202.96.17.1/24:69 202.96.17.1/24:79 202.96.17.1/24:80 202.96.17.1/24:81 202.96.17.1/24:85 202.96.17.1/24:105 202.96.17.1/24:109 202.96.17.1/24:110 202.96.17.1/24:111 202.96.17.1/24:113 202.96.17.1/24:123 202.96.17.1/24:135 202.96.17.1/24:137 202.96.17.1/24:138 202.96.17.1/24:139 202.96.17.1/24:143 202.96.17.1/24:161 202.96.17.1/24:179 202.96.17.1/24:222 202.96.17.1/24:264 202.96.17.1/24:384 202.96.17.1/24:389 202.96.17.1/24:402 202.96.17.1/24:407 202.96.17.1/24:443 202.96.17.1/24:444 202.96.17.1/24:445 202.96.17.1/24:446 202.96.17.1/24:465 202.96.17.1/24:500 202.96.17.1/24:502 202.96.17.1/24:512 202.96.17.1/24:513 202.96.17.1/24:514 202.96.17.1/24:515 202.96.17.1/24:523 202.96.17.1/24:524 202.96.17.1/24:540 202.96.17.1/24:548 202.96.17.1/24:554 202.96.17.1/24:587 202.96.17.1/24:617 202.96.17.1/24:623 202.96.17.1/24:689 202.96.17.1/24:705 202.96.17.1/24:771 202.96.17.1/24:783 202.96.17.1/24:873 202.96.17.1/24:888 202.96.17.1/24:902 202.96.17.1/24:910 202.96.17.1/24:912 202.96.17.1/24:921 202.96.17.1/24:993 202.96.17.1/24:995 202.96.17.1/24:998 202.96.17.1/24:1000 202.96.17.1/24:1024 202.96.17.1/24:1030 202.96.17.1/24:1035 202.96.17.1/24:1090 202.96.17.1/24:1098 202.96.17.1/24:1099 202.96.17.1/24:1100 202.96.17.1/24:1101 202.96.17.1/24:1102 202.96.17.1/24:1103 202.96.17.1/24:1128 202.96.17.1/24:1129 202.96.17.1/24:1158 202.96.17.1/24:1199 202.96.17.1/24:1211 202.96.17.1/24:1220 202.96.17.1/24:1234 202.96.17.1/24:1241 202.96.17.1/24:1300 202.96.17.1/24:1311 202.96.17.1/24:1352 202.96.17.1/24:1433 202.96.17.1/24:1434 202.96.17.1/24:1435 202.96.17.1/24:1440 202.96.17.1/24:1494 202.96.17.1/24:1521 202.96.17.1/24:1530 202.96.17.1/24:1533 202.96.17.1/24:1581 202.96.17.1/24:1582 202.96.17.1/24:1604 202.96.17.1/24:1720 202.96.17.1/24:1723 202.96.17.1/24:1755 202.96.17.1/24:1811 202.96.17.1/24:1900 202.96.17.1/24:2000 202.96.17.1/24:2001 202.96.17.1/24:2049 202.96.17.1/24:2082 202.96.17.1/24:2083 202.96.17.1/24:2100 202.96.17.1/24:2103 202.96.17.1/24:2121 202.96.17.1/24:2199 202.96.17.1/24:2207 202.96.17.1/24:2222 202.96.17.1/24:2323 202.96.17.1/24:2362 202.96.17.1/24:2375 202.96.17.1/24:2380 202.96.17.1/24:2381 202.96.17.1/24:2525 202.96.17.1/24:2533 202.96.17.1/24:2598 202.96.17.1/24:2601 202.96.17.1/24:2604 202.96.17.1/24:2638 202.96.17.1/24:2809 202.96.17.1/24:2947 202.96.17.1/24:2967 202.96.17.1/24:3000 202.96.17.1/24:3037 202.96.17.1/24:3050 202.96.17.1/24:3057 202.96.17.1/24:3128 202.96.17.1/24:3200 202.96.17.1/24:3217 202.96.17.1/24:3273 202.96.17.1/24:3299 202.96.17.1/24:3306 202.96.17.1/24:3311 202.96.17.1/24:3312 202.96.17.1/24:3389 202.96.17.1/24:3460 202.96.17.1/24:3500 202.96.17.1/24:3628 202.96.17.1/24:3632 202.96.17.1/24:3690 202.96.17.1/24:3780 202.96.17.1/24:3790 202.96.17.1/24:3817 202.96.17.1/24:4000 202.96.17.1/24:4322 202.96.17.1/24:4433 202.96.17.1/24:4444 202.96.17.1/24:4445 202.96.17.1/24:4659 202.96.17.1/24:4679 202.96.17.1/24:4848 202.96.17.1/24:5000 202.96.17.1/24:5038 202.96.17.1/24:5040 202.96.17.1/24:5051 202.96.17.1/24:5060 202.96.17.1/24:5061 202.96.17.1/24:5093 202.96.17.1/24:5168 202.96.17.1/24:5247 202.96.17.1/24:5250 202.96.17.1/24:5351 202.96.17.1/24:5353 202.96.17.1/24:5355 202.96.17.1/24:5400 202.96.17.1/24:5405 202.96.17.1/24:5432 202.96.17.1/24:5433 202.96.17.1/24:5498 202.96.17.1/24:5520 202.96.17.1/24:5521 202.96.17.1/24:5554 202.96.17.1/24:5555 202.96.17.1/24:5560 202.96.17.1/24:5580 202.96.17.1/24:5601 202.96.17.1/24:5631 202.96.17.1/24:5632 202.96.17.1/24:5666 202.96.17.1/24:5800 202.96.17.1/24:5814 202.96.17.1/24:5900 202.96.17.1/24:5910 202.96.17.1/24:5920 202.96.17.1/24:5984 202.96.17.1/24:5985 202.96.17.1/24:5986 202.96.17.1/24:6000 202.96.17.1/24:6050 202.96.17.1/24:6060 202.96.17.1/24:6070 202.96.17.1/24:6080 202.96.17.1/24:6082 202.96.17.1/24:6101 202.96.17.1/24:6106 202.96.17.1/24:6112 202.96.17.1/24:6262 202.96.17.1/24:6379 202.96.17.1/24:6405 202.96.17.1/24:6502 202.96.17.1/24:6503 202.96.17.1/24:6504 202.96.17.1/24:6542 202.96.17.1/24:6660 202.96.17.1/24:6661 202.96.17.1/24:6667 202.96.17.1/24:6905 202.96.17.1/24:6988 202.96.17.1/24:7001 202.96.17.1/24:7021 202.96.17.1/24:7071 202.96.17.1/24:7080 202.96.17.1/24:7144 202.96.17.1/24:7181 202.96.17.1/24:7210 202.96.17.1/24:7443 202.96.17.1/24:7510 202.96.17.1/24:7579 202.96.17.1/24:7580 202.96.17.1/24:7700 202.96.17.1/24:7770 202.96.17.1/24:7777 202.96.17.1/24:7778 202.96.17.1/24:7787 202.96.17.1/24:7800 202.96.17.1/24:7801 202.96.17.1/24:7879 202.96.17.1/24:7902 202.96.17.1/24:8000 202.96.17.1/24:8001 202.96.17.1/24:8008 202.96.17.1/24:8014 202.96.17.1/24:8020 202.96.17.1/24:8023 202.96.17.1/24:8028 202.96.17.1/24:8030 202.96.17.1/24:8080 202.96.17.1/24:8081 202.96.17.1/24:8082 202.96.17.1/24:8087 202.96.17.1/24:8090 202.96.17.1/24:8095 202.96.17.1/24:8161 202.96.17.1/24:8180 202.96.17.1/24:8205 202.96.17.1/24:8222 202.96.17.1/24:8300 202.96.17.1/24:8303 202.96.17.1/24:8333 202.96.17.1/24:8400 202.96.17.1/24:8443 202.96.17.1/24:8444 202.96.17.1/24:8503 202.96.17.1/24:8800 202.96.17.1/24:8812 202.96.17.1/24:8834 202.96.17.1/24:8880 202.96.17.1/24:8888 202.96.17.1/24:8889 202.96.17.1/24:8890 202.96.17.1/24:8899 202.96.17.1/24:8901 202.96.17.1/24:8902 202.96.17.1/24:8903 202.96.17.1/24:9000 202.96.17.1/24:9002 202.96.17.1/24:9060 202.96.17.1/24:9080 202.96.17.1/24:9081 202.96.17.1/24:9084 202.96.17.1/24:9090 202.96.17.1/24:9099 202.96.17.1/24:9100 202.96.17.1/24:9111 202.96.17.1/24:9152 202.96.17.1/24:9200 202.96.17.1/24:9390 202.96.17.1/24:9391 202.96.17.1/24:9443 202.96.17.1/24:9495 202.96.17.1/24:9809 202.96.17.1/24:9810 202.96.17.1/24:9811 202.96.17.1/24:9812 202.96.17.1/24:9813 202.96.17.1/24:9814 202.96.17.1/24:9815 202.96.17.1/24:9855 202.96.17.1/24:9999 202.96.17.1/24:10000 202.96.17.1/24:10001 202.96.17.1/24:10008 202.96.17.1/24:10050 202.96.17.1/24:10051 202.96.17.1/24:10080 202.96.17.1/24:10098 202.96.17.1/24:10162 202.96.17.1/24:10202 202.96.17.1/24:10203 202.96.17.1/24:10443 202.96.17.1/24:10616 202.96.17.1/24:10628 202.96.17.1/24:11000 202.96.17.1/24:11099 202.96.17.1/24:11211 202.96.17.1/24:11234 202.96.17.1/24:11333 202.96.17.1/24:12174 202.96.17.1/24:12203 202.96.17.1/24:12221 202.96.17.1/24:12345 202.96.17.1/24:12397 202.96.17.1/24:12401 202.96.17.1/24:13364 202.96.17.1/24:13500 202.96.17.1/24:13838 202.96.17.1/24:14330 202.96.17.1/24:15200 202.96.17.1/24:16102 202.96.17.1/24:17185 202.96.17.1/24:17200 202.96.17.1/24:18881 202.96.17.1/24:19300 202.96.17.1/24:19810 202.96.17.1/24:20010 202.96.17.1/24:20031 202.96.17.1/24:20034 202.96.17.1/24:20101 202.96.17.1/24:20111 202.96.17.1/24:20171 202.96.17.1/24:20222 202.96.17.1/24:22222 202.96.17.1/24:23472 202.96.17.1/24:23791 202.96.17.1/24:23943 202.96.17.1/24:25000 202.96.17.1/24:25025 202.96.17.1/24:26000 202.96.17.1/24:26122 202.96.17.1/24:27000 202.96.17.1/24:27017 202.96.17.1/24:27888 202.96.17.1/24:28222 202.96.17.1/24:28784 202.96.17.1/24:30000 202.96.17.1/24:30718 202.96.17.1/24:31001 202.96.17.1/24:31099 202.96.17.1/24:32764 202.96.17.1/24:32913 202.96.17.1/24:34205 202.96.17.1/24:34443 202.96.17.1/24:37718 202.96.17.1/24:38080 202.96.17.1/24:38292 202.96.17.1/24:40007 202.96.17.1/24:41025 202.96.17.1/24:41080 202.96.17.1/24:41523 202.96.17.1/24:41524 202.96.17.1/24:44334 202.96.17.1/24:44818 202.96.17.1/24:45230 202.96.17.1/24:46823 202.96.17.1/24:46824 202.96.17.1/24:47001 202.96.17.1/24:47002 202.96.17.1/24:48899 202.96.17.1/24:49152 202.96.17.1/24:50000 202.96.17.1/24:50001 202.96.17.1/24:50002 202.96.17.1/24:50003 202.96.17.1/24:50004 202.96.17.1/24:50013 202.96.17.1/24:50500 202.96.17.1/24:50501 202.96.17.1/24:50502 202.96.17.1/24:50503 202.96.17.1/24:50504 202.96.17.1/24:52302 202.96.17.1/24:55553 202.96.17.1/24:57772 202.96.17.1/24:62078 202.96.17.1/24:62514 202.96.17.1/24:65535] 
bug2 : 没有解析这个/24

**Comment by jiaocoll** [comment]
这个是没有问题的，输出目标的时候是有网段的形式输出，但是实际运行的时候的目标是网段中的每个地址都检测，具体可以详细看一下过程中的日志运行情况。
